### PR TITLE
add polarcap grid, fix mpasa15-3 naming issues

### LINKED ISSUE #152: Add dual-polar VR grid to ccs_config
This is the ccs_config PR for installing the spectral-element dual polar grid. The CAM PR is here https://github.com/ESCOMP/CAM/issues/979.

I'm going to ask we call this the 'POLARCAP' grid. So the component_grids_nuopc.xml entry would look like:

```
  <domain name="ne0np4.POLARCAP.ne30x4">
    <nx>186194</nx> <ny>1</ny>
    <mesh>/glade/work/aherring/grids/var-res/ne0np4.POLARRES.ne30x4/grids/polarcap/POLARCAP_ne30x4_np4_MESH_cdf5.nc</mesh>
    <desc>ne0np4.POLARCAP.ne30x4 is a Spectral Elem 1-deg grid with a 1/4 deg refined region over the Arctic and Antarctica:</desc>
    <support>Test support only</support>
  </domain>
```

We are aiming to complete this installation for the CESM3 release.

### LINKED ISSUE #153: clean up "mpas15-3" grid entries
@slevis-lmwg notes:

> When I type git grep mpasa15-3 in /ccs_config, I get:
>
>```component_grids_mct.xml:  <domain name="mpasa15-3conus">
>component_grids_nuopc.xml:  <domain name="mpasa15-3conus">
>component_grids_nuopc.xml:    <mesh driver="nuopc">$DIN_LOC_ROOT/share/meshes/mpasa15-3.conus_ESMF_desc.210816.nc</mesh>
>modelgrid_aliases_mct.xml:  <model_grid alias="mpasa15-3_mpasa15-3" not_compset="_POP">
>modelgrid_aliases_mct.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_mct.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_mct.xml:    <grid name="ocnice">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:  <model_grid alias="mpasa15-3_mpasa15-3" not_compset="_POP">
>modelgrid_aliases_nuopc.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="ocnice">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:  <model_grid alias="mpasa15-3-conus_mpasa15-3-conus" not_compset="_POP">
>modelgrid_aliases_nuopc.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="ocnice">mpasa15-3</grid>```

>In my copy of component_grids_nuopc.xml I removed "conus" from the name to get things to work. If we prefer a different fix, I'm open to that.

I responded

> Ah, I see. So the problem is that the grid aliases are referencing "mpasa15-3" but it doesn't actually exist in component_grids_nuopc.xml. So we need to clean up moodelgrid_aliases_xxx to only reference "mpasa15-3conus". And it looks like a duplicate grid alias in nuopc.

This ```mpasa15-3conus``` grid is not installed in any other externals. I checked with Bill Skamarock and he said the origins of this partial grid install occurred during a time when we were more aspirational in getting these big grids running in CESM. This grid is not runnable at present, but maybe it might be in the future so I'd just recommend fixing the inconsistencies and not removing ```mpasa15-3conus``` altogether.

@PeterHjortLauritzen @ekluzek

### PR DESCRIPTION
**Pull request by adamrher**
Fixes #152 
Fixes #153 

I verified the new POLARCAP grid alias builds and run with this new ccs_config external. Would someone mind adding the mesh and scrip files to inputdata/share/? Ill then update the paths.

```
/glade/work/aherring/grids/var-res/ne0np4.POLARRES.ne30x4/grids/polarcap/POLARCAP_ne30x4_np4_MESH_cdf5.nc
/glade/work/aherring/grids/var-res/ne0np4.POLARRES.ne30x4/grids/polarcap/POLARCAP_ne30x4_np4_SCRIP.nc
```

Should I first add a creation date to the grid file names? Who should I assign as a reviewer?

### CODE REVIEW

**Comment by adamrher** [comment]
@jedwards4b it looks this was merged before moving the POLARCAP mesh and scrip files to inputdata, and the new entry in ```component_grids_nuopc.xml``` is still pointing to my local mesh file?

**Comment by jedwards4b** [comment]
Oh good grief, so much for my value as a reviewer - can you post a corrected pr today?

**Comment by adamrher** [comment]
If you can copy those two files into inputdata for me, I can make an updated PR today.

**Comment by jedwards4b** [comment]
I copied the mesh file to /glade/campaign/cesm/cesmdata/inputdata/share/meshes/POLARCAP_ne30x4_np4_ESMFmesh_cdf5_c20240222.nc
and the scrip file to 
 /glade/campaign/cesm/cesmdata/inputdata/share/scripgrids/POLARCAP_ne30x4_np4_SCRIP.nc

**Pull request merged**
