### PR TITLE
add develop queue

### PR DESCRIPTION
**Pull request by jedwards4b**
Add the develop queue on derecho.

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]

**Review by ekluzek — APPROVED** [review]
Awesome, thanks so much for taking care of this right away @jedwards4b!

**Comment by ekluzek** [comment]
@jedwards4b can it be setup so that develop is the queue used by default when the number of tasks is less than 128?

**Comment by jedwards4b** [comment]
Because of the 1 hour queue limit I'm not sure that we want that.

**Comment by ekluzek** [comment]
I see what you mean, but we have a lot of single point tests that are much less than an hour and we'll need to add testmods to switch them to develop. I think that will be a little bit of a pain to maintain, but I'll look into it. We are figuring we are going to need to add testing for these single point cases on Casper, so we're figuring that out as well.

But, I'll let you decide how best to handle whether this should be default or not...

**Comment by jedwards4b** [comment]
I think you should move these tests to casper.

**Pull request merged**
