### PR TITLE
fix nag build on izumi

### PR DESCRIPTION
**Pull request by jedwards4b**
Fix path to nag_mpi_argument.txt in nag.cmake

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]
Looks good, as long as you planned on removing the mira cmake file.

**Comment by jedwards4b** [comment]
I did.   I'm still having trouble building a test SMS.f19_f19_mg17.F2000climo.izumi_nag it's hanging in the cdeps build, still looking into it.

**Comment by jedwards4b** [comment]
This fix requires also https://github.com/ESCOMP/CDEPS/pull/142

**Comment by jedwards4b** [comment]
Now hitting a problem in the lnd build - @fischer-ncar is this a known issue?
Panic: /home/jedwards/cesm2_x_alpha/components/clm/src/fates/parteh/PRTAllometricCNPMod.F90: Unexpected expr node type 432
Internal Error -- please report this bug
Abort

**Comment by fischer-ncar** [comment]
I believe land only builds with debugging turned on for nag.

**Pull request merged**
