### PR TITLE
MizuRoute lake grids

### LINKED ISSUE #67: Add some new grids for mizuRoute with Lakes
We need to add some new grids for mizuRoute that will have lakes in them. The grid is different when lakes are explicitly modeled versus grids that don't have lakes.

The component grids for HDMAmz will also need a lake version.

### PR DESCRIPTION
**Pull request by ekluzek**
This adds some new grids for mizuRoute lake HDMA-lake option, and also changes the mizuRoute grid aliases to the convention discussed previously.

Fixes #67 
Uses the convention as addressed in #70

### CODE REVIEW

**Review by fischer-ncar — APPROVED** [review]
I don't think you need to do any additional testing.

**Review by jedwards4b — APPROVED** [review]
I DO think that aliases are intended to be short and these are getting to be too long for my comfort, but we've already discussed this.

**Comment by ekluzek** [comment]
I ran the test SMS_Ld1_D.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default and it PASSes.

**Comment by ekluzek** [comment]
I just looked at the results of query_config --grids, and I realize that I didn't fix all of the mizuRoute grids. I thought I had fixed them, but these still need to be changed:

hcru_hcru_mt13_rMERIT hcru_hcru_mt13_rHDMA f09_f09_mg17_rHDMA f09_f09_mg17_rMERIT f19_f19_mg17_rHDMA f19_f19_mg17_rMERIT

**Comment by ekluzek** [comment]
Oh, the problem is that there are mizuRoute grids defined for MCT -- but I should just remove those.

**Comment by ekluzek** [comment]
OK I removed the mizuRoute grids from MCT, and did a namelist check for the new aliases, and they all work. So this is ready from my perspective. @fischer-ncar can you merge it now?

**Pull request merged**
